<a href="https://colab.research.google.com/github/DzhuJK/KSVD/blob/main/%D0%9B%D0%A01_%D0%9B%D0%B0%D1%86.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Була присутня на парі 03.02.2026

In [ ]:
import numpy as np

np.__version__

'2.0.2'

In [ ]:
v = np.array([1, 2, 3, 4, 5], dtype = float)
v

array([1., 2., 3., 4., 5.])

In [ ]:
v[0]

np.float64(1.0)

In [ ]:
v[-1]

np.float64(5.0)

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a[1, 2]

np.int64(6)

In [ ]:
a[0,0]

np.int64(1)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

6

In [ ]:
a.shape

(2, 3)

In [ ]:
a = np.array([[1, 3, 4], [5, 7, 8], [3, 6, 9]])
a

array([[1, 3, 4],
       [5, 7, 8],
       [3, 6, 9]])

In [ ]:
b = np.matrix([[1, 3, 4], [5, 7, 8], [3, 6, 9]])
b

matrix([[1, 3, 4],
        [5, 7, 8],
        [3, 6, 9]])

In [ ]:
diag_a = np.diag(a)
diag_a

array([1, 7, 9])

In [ ]:
a_diag = np.diag(diag_a)
a_diag

array([[1, 0, 0],
       [0, 7, 0],
       [0, 0, 9]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.random.randint(11, size=(4,4))

array([[ 1,  0,  3,  7],
       [ 0, 10,  7, 10],
       [ 7,  9,  2,  5],
       [ 5,  1,  6,  5]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 20, 5)

array([ 0.,  5., 10., 15., 20.])

In [ ]:
np.ones((3, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
a = np.array([[1, 3, 4], [5, 7, 8], [3, 6, 9]])
a

array([[1, 3, 4],
       [5, 7, 8],
       [3, 6, 9]])

In [ ]:
a.transpose()

array([[1, 5, 3],
       [3, 7, 6],
       [4, 8, 9]])

In [ ]:
a.T

array([[1, 5, 3],
       [3, 7, 6],
       [4, 8, 9]])

In [ ]:
a = np.array([[3, 2], [1, 4]])
a

array([[3, 2],
       [1, 4]])

In [ ]:
a_det = np.linalg.det(a)
a_det.round(2)

np.float64(10.0)

In [ ]:
a = np.matrix([[1, 2, 3], [4, 5, 6]])
c = 5 * a
c

matrix([[ 5, 10, 15],
        [20, 25, 30]])

In [ ]:
a = np.matrix([[1, 6, 2], [8, 2, 7]])
b = np.matrix([[7, 2, 5], [9, 9, 12]])
c = a + b
c

matrix([[ 8,  8,  7],
        [17, 11, 19]])

In [ ]:
a = np.matrix([[1, 2], [4, 5]])
b = np.matrix([[7, 8], [9, 1]])
c = np.dot(a, b)
c

matrix([[25, 10],
        [73, 37]])

In [ ]:
np.multiply(a, b)

matrix([[ 7, 16],
        [36,  5]])

In [ ]:
a/b

matrix([[0.14285714, 0.25      ],
        [0.44444444, 5.        ]])

In [ ]:
np.divide(a, b)

matrix([[0.14285714, 0.25      ],
        [0.44444444, 5.        ]])

In [ ]:
a = np.matrix([[1, -3], [2, 5]])

a_inv = np.linalg.inv(a)
a_inv

matrix([[ 0.45454545,  0.27272727],
        [-0.18181818,  0.09090909]])

In [ ]:
rank = np.linalg.matrix_rank(a)
rank

np.int64(2)

In [ ]:
a = np.array([[1, 6, 3], [8, 2, 7]])
b = np.array([[8, 1, 5], [6, 9, 12]])

c1 =  a*b
print("Поелементний добуток матриць:")
print(c1)

Поелементний добуток матриць:
[[ 8  6 15]
 [48 18 84]]


In [ ]:
a = np.array([[5, -2, 3],
              [0,  3, 2],
              [1, -1, 0]])


eigenvalues, eigenvectors = np.linalg.eig(a)


In [ ]:
print("Власні числа:")
eigenvalues

Власні числа:


array([-0.1925824,  5.1925824,  3.       ])

In [ ]:
print("\nВласні вектори:")
eigenvectors


Власні вектори:


array([[-5.70197420e-01,  9.76291233e-01, -7.07106781e-01],
       [-4.36124939e-01,  1.45876610e-01, -7.07106781e-01],
       [ 6.96182404e-01,  1.59923244e-01,  8.00941814e-17]])